<a href="https://colab.research.google.com/github/ssoma2mc/MATH264/blob/main/Chapter_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Importing libraries or module

In [ ]:
# import libraries
import numpy as np

# import everything from sympy module
from sympy import *


# Vector-scalar multiplication

In [ ]:
# a scalar
s = -1/2

# a vector
b = np.array([3,4])

# print them
print(b*s)

# Question: Does vector b need to be a numpy array? What happens if it's a list?

[-1.5 -2. ]


In [ ]:
# Scalar-vector addition
s = 3.5
v=np.arrary([1,2,3])
print(v)
print(s+v)

AttributeError: ignored

In [ ]:
# Row vector
r = np.array([ [1,2,3] ])

# orientationless array
l = np.array([1,2,3])

# Vector transpose

In [ ]:
# Row vector
r = np.array([ [1,2,3] ])

# orientationless array
l = np.array([1,2,3])

In [ ]:
# print out the vector and its transpos
print(r)
print(np.transpose(r))

# what about l and l transpose?
print(l)
print(np.transpose(l))

[[1 2 3]]
[[1]
 [2]
 [3]]
[1 2 3]
[1 2 3]


# Row Reduction of Matrices (LE2)

***Definition 1.2.6***.  A matrix is in reduced row echelon form (RREF) if:
 Call these terms pivots.



Every matrix has a unique reduced row echelon form. If

1.   The leading term (first nonzero term) of each nonzero row is a 1.
2.   Each pivot is to the right of every higher pivot.
3.   Each term above or below a pivot is zero.
4.   All rows of zeroes are at the bottom of the matrix.

if $A$ is a matrix, we write $RREF(A)$ for the reduced row echelon form of that matrix.




Cheking if a matrix is in RREF

$A=\left[\begin{array}{ccc}2 & 1 & 0 \\ 1 & 0 & 0 \\ 3 & -1 & 1\end{array}\right]$


In [ ]:
T=Matrix([[-3,6,2,8],[-1,2,5,7],[2,-4,-3,-7],[1,-2,-1,-3]])
print(T)
T.rref()

Matrix([[-3, 6, 2, 8], [-1, 2, 5, 7], [2, -4, -3, -7], [1, -2, -1, -3]])


(Matrix([
 [1, -2, 0, -2],
 [0,  0, 1,  1],
 [0,  0, 0,  0],
 [0,  0, 0,  0]]), (0, 2))

In [ ]:
#lets first define the matrix
#A=matrix([[2,1,0],[1,0,0],[3,-1,1]])
#A_rref=A.rref()

A= Matrix([[2,1,0],[1,0,0],[3,-1,1]]);
print(A==A.rref())
print(A.rref())

False
(Matrix([
[1, 0, 0],
[0, 1, 0],
[0, 0, 1]]), (0, 1, 2))


In [ ]:
M = Matrix([[1, 0, 1, 3], [2, 3, 4, 7], [-1, -3, -3, -4]])
print("Matrix : {} ".format(M))

# Use sympy.rref() method
#The pivots=fale means it does not show the location of pivots in each row
M_rref = M.rref()
print("The Row echelon form of matrix M and the pivot columns : {}".format(M_rref))

#In case you do not want to see the location of pivot in each columns
print("The Row echelon form of matrix M and the pivot columns : {}".format(M.rref(pivots=false)))

#If you really like to see the matrix as a 2D matrix format. you can use numpy to change the matrix to numpy format and that will let you see it
#print(np.matrix(M_rref))

Matrix : Matrix([[1, 0, 1, 3], [2, 3, 4, 7], [-1, -3, -3, -4]]) 
The Row echelon form of matrix M and the pivot columns : (Matrix([
[1, 0,   1,   3],
[0, 1, 2/3, 1/3],
[0, 0,   0,   0]]), (0, 1))
The Row echelon form of matrix M and the pivot columns : Matrix([[1, 0, 1, 3], [0, 1, 2/3, 1/3], [0, 0, 0, 0]])


#Row Operation
##1. Swapping Two Row

In [ ]:
#Method 1, we will use append to add an extra row and then later we delete it after switching both rows
S=np.array([[1,1],[2,2],[3,3]])
print(S)
row=np.array([1,1])

# we add a new row to the matrix S
TT=np.append(S,[row],axis= 0)
# Now, we rearrang the row 1 to be row 3 and row 3 to be row 4
TT[0,:]=TT[2,:]
TT[2,:]=TT[3,:]
#Finally we will delete row 4 since we do not need it
TT=np.delete(TT,3,0)
print(TT)



[[1 1]
 [2 2]
 [3 3]]
[[3 3]
 [2 2]
 [1 1]]


# Here is another way, I think this one is much easier:


In [ ]:
#Method 2, Creating a row vecotr  and the make a switch
SS=np.array([[1,1],[2,2],[3,3]])
print(SS)
#Creating a vector row
R1=np.array([[1,1]])
#changeing row 1 to be the row 3 and then row 3 to be the vecotr row
SS[0,:]=SS[2,:]
SS[2,:]=R1
print(SS)

[[1 1]
 [2 2]
 [3 3]]
[[3 3]
 [2 2]
 [1 1]]


In [ ]:
#This one is more general, since we defien a function
def swapp_row(Matrix,row1,row2):
  r=row1
  s=row2
  print(Matrix)
  M=np.array(Matrix)
  Row=np.array(M[r,:])
  M[r,:]=M[s,:]
  M[s,:]=Row
  return M

In [ ]:
swapp_row([[1,2],[3,4],[4,5]],0,2)



[[1, 2], [3, 4], [4, 5]]


array([[4, 5],
       [3, 4],
       [1, 2]])

#2. Multiply a row by a nonzero constant.



In [ ]:
def scalar_row(M,r,a):
  #M is the matrix r is the row and a is the scalar
  print(M)
  M=np.array(M)
  M[r,:]=float(a)*M[r,:]
  return M

#3. Add a constant multiple of one row to another row

In [ ]:
def multiple_rowconstant(M,r,s,a):
  #M is the matrix r is the row and a is the scalar
  print(M)
  M=np.array(M)
  M[r,:]=a*M[s,:]+M[r,:]
  return M

In [ ]:
multiple_rowconstant([[1,1],[2,2]],0,1,5)

In [ ]:
T=np.array([1,2,3])
S=np.array([2,3,4])
Summ=T+S
print(Summ)

[3 5 7]
