<a href="https://colab.research.google.com/github/Reben80/LinearAlgebra_DataScience/blob/main/Tutorial_Assignment_Three_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


# Python Tutorial: Conditional Statements and Loops

1. Introduction
 Conditional statements and loops allow your code to make decisions and perform repetitive tasks.
In this tutorial, we'll explore the basics of these constructs with some mathematical examples.

2. Conditional Statements (`if`, `elif`, and `else`)

The `if` statement checks a condition. If that condition is `True`, it executes a block of code.


In [3]:

x = 5
if x > 0:
    # This will print because x is positive.
    print("x is positive!")

# You can add an `else` block for when the `if` condition is `False`.

x = -5
if x > 0:
    print("x is positive!")
else:
    # This will print because x is not positive.
    print("x is not positive!")




x is positive!
x is not positive!


##  For more than two possible conditions, use the `elif` statement.

In [4]:


x = 0
if x > 0:
    print("x is positive!")
elif x == 0:
    # This will print because x is zero.
    print("x is zero!")
else:
    print("x is negative!")

# 3. Loops (`for` and `while` loops)

# The `for` loop in Python iterates over sequences like lists or ranges.

# Looping through a list
primes = [2, 3, 5, 7, 11]
for prime in primes:
    print(prime)



x is zero!
2
3
5
7
11


## Looping using a range

In [5]:
#This will print numbers from 0 to 4.
for i in range(5):
    print(i)

# The `while` loop runs as long as a condition is true.

x = 5
while x > 0:
    # This will print numbers from 5 down to 1.
    print(x)
    x -= 1



0
1
2
3
4
5
4
3
2
1


## 4. Mixing Conditionals and Loops

Loop through a list and use conditionals to check if numbers are even or odd.

In [6]:


numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9]
for num in numbers:
    if num % 2 == 0:
        # Prints if the number is even.
        print(f"{num} is even!")
    else:
        # Prints if the number is odd.
        print(f"{num} is odd!")

# 5. Challenge: Sum of First n Fibonacci Numbers

def fibonacci_sum(n):
    # If n is zero or negative, the sum is 0.
    if n <= 0:
        return 0

    a, b = 0, 1
    sum_fib = 1

    # Loop through and compute the sum.
    for _ in range(n-1):
        a, b = b, a + b
        sum_fib += b

    return sum_fib

1 is odd!
2 is even!
3 is odd!
4 is even!
5 is odd!
6 is even!
7 is odd!
8 is even!
9 is odd!


# Testing the function

In [7]:

print(fibonacci_sum(5))  # Output should be 12 (0 + 1 + 1 + 2 + 3 + 5)




12


# Conclusion
Mastery of conditional statements and loops enables tackling a wide range of problems in linear algebra.

## Assinment 4

Most of the python code you need for Assinment 4 you already have, but one of the function it maybe useulf is transpose, below we illustrate:


In [15]:
# I don't understand what to do



# Create a sample 3x2 matrix for demonstration

#A = np.array([[1, 2],
#                          [3, 4],
#                          [5, 6]])

sample_matrix = np.array([[1, 2], [3, 4], [5, 6]])
print (sample_matrix)

# Transpose the matrix using numpy's '.T' attribute
sample_matrix_transposed = A.T
print (sample_matrix_transposed)

# Display the original and transposed matrices
#print("Original matrix:")
print(sample_matrix)

#print("Transposed matrix:")
print(sample_matrix_transposed)


[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]
