<a href="https://colab.research.google.com/github/Reben80/LinearAlgebra_DataScience/blob/main/Tutorial_Assignment_Two.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

 # Creating a Matrix using numpy


In [2]:
D=np.array([[1,2,3],[4,5,6]])

print(f"The matrix D is :{D}")



# Creating matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 2], [2, 2]])

print("Matrix A:")
print(A)

print("\nMatrix B:") # \n new row
print(B)





The matrix D is :[[1 2 3]
 [4 5 6]]
Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[2 2]
 [2 2]]


## Basic Matrix Operation

In [3]:

# Addition
C = A + B
print("\nAddition (A + B):")
print(C)

# Subtraction
D = A - B
print("\nSubtraction (A - B):")
print(D)

# Scalar Multiplication
E = 3 * A
print("\nScalar Multiplication (3 * A):")
print(E)

# Matrix Multiplication
F = np.dot(A, B)
print("\nMatrix Multiplication (A * B):")
print(F)

# Transpose Every row become column and column become row... that is first row become first column, and second row become second coumn etc......
G = A.T
print("\nTranspose of A:")
print(G)


# Note: Always ensure matrices have the correct dimensions for operations



Addition (A + B):
[[3 4]
 [5 6]]

Subtraction (A - B):
[[-1  0]
 [ 1  2]]

Scalar Multiplication (3 * A):
[[ 3  6]
 [ 9 12]]

Matrix Multiplication (A * B):
[[ 6  6]
 [14 14]]

Transpose of A:
[[1 3]
 [2 4]]


## Matrix Indexing

In [4]:


# Creating a 3x4 matrix
M = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("Matrix M:")
print(M)

# Indexing
# Single element indexing
element_1_2 = M[0, 1]  # Accessing the element in the first row and second column
print(f"\nElement at [0, 1]: {element_1_2}")

# Row indexing
row_2 = M[1, :]  # Accessing the second row : mean everytiong column here
print("\nRow 2:")
print(row_2)

# Column indexing
col_3 = M[:, 2]  # Accessing the third column
print("\nColumn 3:")
print(col_3)

# Sub-matrix indexing
sub_matrix = M[1:, 1:3]  # Accessing the sub-matrix starting from the second row and columns 2 and 3
print("\nSub-matrix from row 2 and columns 2-3:")
print(sub_matrix)

# Conditional indexing
greater_than_6 = M[M > 6]  # Get elements greater than 6
print("\nElements greater than 6:")
print(greater_than_6)

# Changing an element value using indexing
M[2, 3] = 0  # Setting the element at the third row and fourth column to 0
print("\nMatrix M after updating [2, 3]:")
print(M)

# Note: Python indexing starts from 0, so the first row/column is index 0, the second is index 1, and so on.

subMatrixM=M[0:2,0:2]  # whenver you say from 0 to 3 in python that python take 0,1 and 2.... it does NOT take 3
print(subMatrixM)


Matrix M:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Element at [0, 1]: 2

Row 2:
[5 6 7 8]

Column 3:
[ 3  7 11]

Sub-matrix from row 2 and columns 2-3:
[[ 6  7]
 [10 11]]

Elements greater than 6:
[ 7  8  9 10 11 12]

Matrix M after updating [2, 3]:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11  0]]
[[1 2]
 [5 6]]


## Special Matrices in Python using Numpy

In linear algebra, there are several special matrices that are widely used due to their unique properties. Using the numpy library in Python, we can easily create and work with these matrices. In this tutorial, we'll explore some of the most common special matrices.

1. Identity Matrix
Description: A square matrix in which all the elements of the principal diagonal are ones and all other elements are zeros.

In [5]:

I = np.eye(3)
print("Identity Matrix 3x3:")
print(I)


Identity Matrix 3x3:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


2. Zero Matrix
Description: A matrix in which all the elements are zeros.

In [6]:
Z = np.zeros((3, 4))
print("\nZero Matrix 3x4:")
print(Z)



Zero Matrix 3x4:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


3. Ones Matrix
Description: A matrix in which all the elements are ones.

In [7]:
O = np.ones((3, 4))
print("\nOnes Matrix 3x4:")
print(O)


Ones Matrix 3x4:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


4. Random Matrix (between 0 and 1)
Description: A matrix with elements generated randomly between 0 and 1.

In [8]:
R1 = np.random.rand(3, 4)
print("\nRandom Matrix 3x4 (between 0 and 1):")
print(R1)



Random Matrix 3x4 (between 0 and 1):
[[0.06308013 0.95244414 0.40418504 0.96950198]
 [0.87041085 0.38177576 0.81959372 0.54428555]
 [0.51562702 0.58422718 0.5835091  0.12455525]]


5. Random Matrix (between 1 and n)
Description: A matrix with random integer elements between a specified range (inclusive).

In [9]:
n = 10
R2 = np.random.randint(1, n+1, size=(3, 4))
print(f"\nRandom Matrix 3x4 (between 1 and {n}):")
print(R2)


Random Matrix 3x4 (between 1 and 10):
[[ 2  9  6  5]
 [ 6  6  7 10]
 [ 2  1  6  5]]


In [10]:
M
print(M)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11  0]]
