<a href="https://colab.research.google.com/github/Reben80/LinearAlgebra_DataScience/blob/main/Tutorial_Assignment_Five_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Matrix Multiplication in Python

## First Method (Pure Python not pakcage)
This notebook demonstrates the multiplication of two matrices using a custom function `Multiplication264`. The function checks for matrix size compatibility and performs multiplication if possible.


In [4]:
def Multiplication264(A, B):
    """
    Perform matrix multiplication on two matrices A and B.

    Parameters:
    A (list of list of int/float): The first matrix.
    B (list of list of int/float): The second matrix.

    Returns:
    list of list of int/float: The resultant matrix after multiplication,
    or a string indicating that the matrices cannot be multiplied.
    """

    # Determine the dimensions of the matrices
    rows_A = len(A)             # Number of rows in matrix A
    cols_A = len(A[0])          # Number of columns in matrix A
    rows_B = len(B)             # Number of rows in matrix B
    cols_B = len(B[0])          # Number of columns in matrix B

    # Check if the number of columns in A equals the number of rows in B
    if cols_A != rows_B:
        return "Matrices cannot be multiplied"

    # Initialize a result matrix with zeros.
    # Size of the resultant matrix is rows_A x cols_B
    result = [[0 for _ in range(cols_B)] for _ in range(rows_A)]

    # Perform the matrix multiplication
    for i in range(rows_A):
        for j in range(cols_B):
            for k in range(cols_A):
                # Accumulate the sum of products
                result[i][j] += A[i][k] * B[k][j]

    return result


## Testing the Function

Now, let's test the `Multiplication264` function with an example.


In [5]:
# Define two matrices
A = [[1, 2], [3, 4]]
B = [[5, 6], [7, 8]]

# Call the Multiplication264 function
result = Multiplication264(A, B)

# Print the input matrices and the result
print("Matrix A:", A)
print("Matrix B:", B)
print("Product of A and B:", result)


Matrix A: [[1, 2], [3, 4]]
Matrix B: [[5, 6], [7, 8]]
Product of A and B: [[19, 22], [43, 50]]


-------
--------


## Second Method (Using Package) : Matrix Multiplication Using NumPy

NumPy is a powerful library for numerical computing in Python. It provides a highly optimized method for matrix multiplication. In this section, we will demonstrate how to multiply matrices using NumPy.


In [6]:
import numpy as np


# Define two matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Matrix multiplication using NumPy
result_numpy = np.dot(A, B)

print("Matrix A (NumPy):\n", A)
print("Matrix B (NumPy):\n", B)
print("Product of A and B using NumPy:\n", result_numpy)



Matrix A (NumPy):
 [[1 2]
 [3 4]]
Matrix B (NumPy):
 [[5 6]
 [7 8]]
Product of A and B using NumPy:
 [[19 22]
 [43 50]]


-------
-------


## Comparing the two method

We can use random to create two matrix with sutiable size and then multiply them using both method and finally take absolute difference to see is zero ( or almost zero ). This way we can be sure there are no mistake in our code

In [ ]:
import random
# Function to generate a random matrix of a given size
def generate_random_matrix(rows, cols):
    return [[random.randint(0, 10) for _ in range(cols)] for _ in range(rows)]

# Generate two random matrices with suitable sizes
rows_A = random.randint(2, 5)
cols_A = random.randint(2, 5)
rows_B = cols_A  # To ensure multiplication is possible
cols_B = random.randint(2, 5)

A = generate_random_matrix(rows_A, cols_A)
B = generate_random_matrix(rows_B, cols_B)

# Convert lists to NumPy arrays for NumPy multiplication
A_np = np.array(A)
B_np = np.array(B)

# Perform matrix multiplication using both methods
result_custom = Multiplication264(A, B)
result_numpy = np.dot(A_np, B_np)

# Convert the custom result to a NumPy array for comparison
result_custom_np = np.array(result_custom)

# Compare the results
difference = np.abs(result_custom_np - result_numpy)
is_same = np.all(difference < 1e-10)  # Check if the difference is close to zero

# Output
print("Matrix A:", A)
print("Matrix B:", B)
print("Product using custom method:", result_custom)
print("Product using NumPy:", result_numpy)
print("Difference:", difference)
print("Are the results the same (within a small error margin)?", is_same)


Matrix A: [[3, 9, 6, 7], [1, 6, 3, 2], [1, 0, 7, 0], [9, 10, 1, 3]]
Matrix B: [[9, 1, 4], [4, 10, 3], [1, 0, 8], [2, 2, 0]]
Product using custom method: [[83, 107, 87], [40, 65, 46], [16, 1, 60], [128, 115, 74]]
Product using NumPy: [[ 83 107  87]
 [ 40  65  46]
 [ 16   1  60]
 [128 115  74]]
Difference: [[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
Are the results the same (within a small error margin)? True
